language: elixir

sudo: false

elixir:
  - 1.6

otp_release:
  - 20.3

services:
  - rabbitmq

env:
  - MIX_ENV=test

script:
  - mix credo --strict
  - mix format --check-formatted
  - mix coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
